### ISSUE TITLE
True Lilith: Wierd calculation

### ISSUE THREAD

**Issue by NodBr** [theriftlab/immanuel-python#11]
Hi @theriftlab 

Check this out:

```
from immanuel import charts

subject = charts.Subject('2024-04-29 06:15', '22S54', '43w06')
natal= charts.Natal(subject)

print(natal.objects[6000007])
```

The answer was:

> True Lilith 16°27'33" in Libra, 6th House, Direct

But looking in Astro.com, it should be Virgo, 19º, 5th House, as you can see in the image.

Do you have any idea what I'm doing wrong?

![image](https://github.com/theriftlab/immanuel-python/assets/128865793/e25cd3d0-69d4-4eec-836d-61dca251a1c4)

**Comment by theriftlab** [comment]
This is due to the sheer number of confusing Liliths - if you add all of them you'll see this (Waldemath also being another Lilith):

<img width="274" alt="image" src="https://github.com/theriftlab/immanuel-python/assets/370745/ffc568b0-0ec1-49f9-831b-8fce8e44564b">

Immanuel currently only supports mean and true Lilith. If you run this:

```python
from immanuel import charts
from immanuel.const import chart
from immanuel.setup import settings


settings.objects = [chart.LILITH, chart.TRUE_LILITH]

subject = charts.Subject('2024-04-29 06:15', '22S54', '43w06')
natal = charts.Natal(subject)

for object in natal.objects.values():
    print(object)
```

you should get this:

```
Lilith 23°14'14" in Virgo, 5th House
True Lilith 16°27'33" in Libra, 6th House
```

You'll see Lilith agrees with astro's Lilith ("Mean Lilith" in the list), and True Lilith agrees with astro's "Lilith (o)" which is extra object h13.

Interpolated Lilith isn't in Immanuel, but a quick look at pyswisseph's source code shows it's definitely supported by the ephemeris, so I'll get that added in.

**Comment by NodBr** [comment]
Oh! You're absolutely right.

Thanks a lot.
