### ISSUE TITLE
TR timezone change astro.com differences

### ISSUE THREAD

**Issue by bindu-javelin** [theriftlab/immanuel-python#20]
There is a problem on the charts for Turkey for the birthdates before 2016. There is a timezone changed happened this time. Astro.com showing correct results but this app not unfortunately. 1 hour before the birth time showing accurate results between astro.com and immanuel. 

Astro.com using universal time and sidney time for accuracy. This might be used.

**Comment by theriftlab** [comment]
This is likely due to the TimezoneFinder issue mentioned in the docs: https://github.com/theriftlab/immanuel-python/blob/v1.4.1/docs/2-installation.md

Unfortunately the initialization time for the test 6.x.x versions of the TimezoneFinder package is much longer than the 5.2.x versions. This is probably not a problem for most hobbyist users so you might be able to simply force pip to upgrade TimezoneFinder to the latest version and get a slower but more accurate timezone.

**Comment by theriftlab** [comment]
Actually scratch that, the date/time is not passed to TimezoneFinder. In fact I would presume any offline timezone search would not take historical zones into account since that would increase the download size massively. I wonder if it's worth adding a bypass option into Immanuel where you can pass in the UTC offset manually.

Closing this issue for now since there is currently no practical way to bundle all historical timezones into this package.

**Comment by NodBr** [comment]
Hi @theriftlab .

Maybe there can be an option to pass directly the julian day as a float. 
It's probably easier, since any timestamp needs to be converted to julday to be used on Swiss Ephemerides

**Comment by theriftlab** [comment]
@NodBr that could work too, I'm currently trying out a few different approaches. I'm also wondering if there's an offline solution to historical changes like this that can be packaged up with Immanuel, but it does seem unlikely & impractical :-(
