### ISSUE TITLE
aspects to examples without native is not working

### ISSUE THREAD

**Issue by bindu-javelin** [theriftlab/immanuel-python#21]
in example file you claimed that this can work, but unfortunately the function first parameter only gets native.  

So the below options are not possible for the moment:
It might also be useful to pass transits into a progressed or composite chart. You could even pass a composite chart into another composite chart to view synastry aspects between them.

charts.Natal(transits, aspects_to=composite)
charts.Natal(progressed, aspects_to=composite) 

immanuel/charts.py", line 164, in generate
    self._obliquity = ephemeris.obliquity(self._native.julian_date) AttributeError: 'Transits' object has no attribute 'julian_date'

**Comment by theriftlab** [comment]
What are you trying to accomplish? Can you share more of your code? Every chart needs a `Subject` instance as a first argument, otherwise it has nothing to generate a chart from (the only seeming exception to this is the `Transits` chart which internally generates its own `Subject` instance). The `aspects_to` argument is another chart instance, not a `Subject`.

For example:

```python
from immanuel import charts

native = charts.Subject('2000-01-01 10:00', '32n43', '117w09')
partner = charts.Subject('2001-06-21 18:30', '51n28.69', '0e0.1')

transits = charts.Transits()
composite = charts.Composite(native=native, partner=partner, aspects_to=transits)
```

**Comment by bindu-javelin** [comment]
done
